[package]
name = "llm_globber" # Replace with your desired package name, should match PROJECT_NAME in Makefile
version = "0.1.0" # Or your desired version
authors = ["Ken Simpson <ksimpson@mailchannels.com>"] # Replace with your name and email
edition = "2021" # Or "2018" if you prefer

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] } # Or a more recent version
glob = "0.3" # Or a more recent version
log = "0.4" # Or a more recent version
memmap2 = "0.5" # Or a more recent version
simplelog = "0.12" # Using a more recent version that's available
chrono = "0.4" # Or a more recent version
